# Generated by Django 4.2.6 on 2023-10-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_users_alter_product_content_alter_product_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email пользователя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Пароль пользователя'),
        ),
    ]
