# Generated by Django 4.2.6 on 2023-10-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль пользователя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email пользователя')),
            ],
        ),
    ]
